### ISSUE TITLE
Rendered View

### ISSUE THREAD

**Issue by jmwright** [matthewmaier/platyvue#11]
The current rendered view (not sure if that's the right term) is set up to be in the lower right corner of the network diagram area. This cuts down on the available area for laying out the network. Would it be possible to add some sort of a render drop-down that would allow you to render the network in preset ways into a pop up dialog?

**Comment by jmwright** [comment]
"Separate window" would be a better phrase to use than "pop up dialog".

**Comment by matthewmaier** [comment]
Yep. I plan to make them "tabbed." Just stuck it there so I could see the
output.

**Comment by jmwright** [comment]
Looks like there's a render tab now, but I don't see anything showing up in it. Is this still in progress?

**Comment by matthewmaier** [comment]
I should be back online today. I think you'll be pleased with how the
instructions work now. I added an error message to explain that blankness :)

**Comment by jmwright** [comment]
Great, thanks!

**Comment by jmwright** [comment]
The way the rendered view is set up now is much better, but I can't get it to display anything except the message that at least one node needs both dive and rise links. Here's what I did to try to get something into the render view.

![platyvue_no_render](https://cloud.githubusercontent.com/assets/1015439/9210418/38d5260a-404a-11e5-9c2e-73ff25733ab8.png)

The `Unpacking Checklist` has both dive and rise links, and the `Finished Test Stand` has a rise link.

Also, the rise links don't seem to be auto-hiding like the dive links do.

What have I done wrong? Is there a minimum set of steps that I can follow that should make the document render?

**Comment by matthewmaier** [comment]
To dive from container:
- click on container node
- ctrl-click on a contained node that begins the contained flow
- click 'dive' button

To rise to container:
- click on contained node that ends flow
- ctrl-click on container node
- click 'rise' button

Each node that begins or ends the contained flow needs its own dive/ rise
link to the container node.
The system-generated container node has dive/rise link stubs to clean up
the graph.

**Comment by jmwright** [comment]
Ok, so what was happening was that I was Ctrl-clicking the nodes in the wrong order for the rise. It's the same thing that's bitten me before with the flow direction.
