### ISSUE TITLE
Crash When .plat Extension is Added By the User

### ISSUE THREAD

**Issue by jmwright** [matthewmaier/platyvue#12]
I'm using the latest commit of Platyvue alpha.

Steps to repeat.
1. Click File -> New
2. Click File -> Save As
3. Enter platyvue.plat for file name
4. Click the Save button

The app will crash for me, and I think it's because it expects to append the .plat extension itself.

**Comment by matthewmaier** [comment]
That case is handled.
It doesn't cause a problem for me. I'm using Windows.
It might be that something is going wrong when it tries to deal with files
on Linux.

**Comment by jmwright** [comment]
Odd, everything seems to be in order when looking at the variables after the crash. I guess we'll just have to wait until LiveCode 8 to see if this is fixed in the Linux version.

![platyvue_feeback_08_04_15_2](https://cloud.githubusercontent.com/assets/1015439/9071794/5bed21fe-3ac5-11e5-9ef3-495781dcaa4d.png)
