### ISSUE TITLE
Crash When Adding Custom Tag Info

### ISSUE THREAD

**Issue by jmwright** [matthewmaier/platyvue#13]
OS: Ubuntu 14.04
Version: Commit 52b8022d74fd6ec37c7517e5b7c88f696aaaad62

I may have stepped on a reserved keyword accidentally.

Steps to reproduce crash:
1.  Add a new state
2. Set the title of the state - i.e. "title, Unpacking Checklist"
3. Set new info on the state of "type, UnorderedList"

Error: stack "primary": execution error at line n/a (Object: can't set this property)
- Line 1357 of render

**Comment by jmwright** [comment]
I guess that render isn't the source, but that line number shows up again and again.

![platyvue_feeback_08_04_15](https://cloud.githubusercontent.com/assets/1015439/9071629/54927dd8-3ac4-11e5-98df-05a2cdd8c201.png)

**Comment by matthewmaier** [comment]
Oh, yeah, that seems obvious now. I didn't filter the tags the user can
enter against the reserved words in Platypus. Adding another 'type' tag
probably does screw up the logic somewhere.

**Comment by jmwright** [comment]
Yep. I just confirmed that if I use 'type2' instead of 'type', Platyvue doesn't crash.

**Comment by matthewmaier** [comment]
fixed that
