### ISSUE TITLE
Duplicate Tags

### ISSUE THREAD

**Issue by jmwright** [matthewmaier/platyvue#15]
I'm still trying to wrap my head around Platypus/Platyvue, so I'm not even sure this is a valid thing to do, but here goes.

In creating a state with a checklist in it, I'm trying to define the state/node type of "Unordered List", and then add a list "listitem" for each item in the checklist. The current implementation replaces any listitem tag with the next one I enter, so `listitem, Test stand` followed by `listitem, Concrete block` will result in just the `Concrete block` entry showing up. Am I  going about this the wrong way, or should users be allowed to duplicate tags?

![platyvue_feeback_08_05_15_2](https://cloud.githubusercontent.com/assets/1015439/9095384/faf95ec4-3b84-11e5-81b5-26272b074233.png)

**Comment by matthewmaier** [comment]
Yeah, tags overwrite each other. There isn't a way for the user to directly
enter an array. You might be able to enter a list by hitting return or
alt-return in the popup window.

I think this would be a feature request for a better tag/data creation
interface.
