### ISSUE TITLE
Doubled Buttons

### ISSUE THREAD

**Issue by jmwright** [matthewmaier/platyvue#16]
OS: Ubuntu 15.04
LiveCode Version: 7.0.6
Happens with latest commit of Platyvue: dc38ae00520e97f5d0a9d09068b9e6b5fd1c3aef

The main UI shows a `file` button that is on top of the `info` button for me.

![platyvue_double_button_glitch](https://cloud.githubusercontent.com/assets/1015439/9210224/05ca868e-4049-11e5-95f7-25507cc3be84.png)

**Comment by matthewmaier** [comment]
Okay, that was  a shortcut. I'll fix it.

**Comment by matthewmaier** [comment]
Just two buttons side by side now
