### ISSUE TITLE
Other Uses for Platypus Data Structure

### ISSUE THREAD

**Issue by jmwright** [matthewmaier/platyvue#4]
It occurred to me tonight that the data structure, with states and changes, could maybe be used as a feature tree for a CAD application like CadQuery. Any thoughts on that?

**Comment by matthewmaier** [comment]
Assuming this is what you mean
http://www.bawiki.com/wiki/techniques/feature-tree/
Yes, all it's doing is keeping track of information and pointers between
information. The underlying logic could be built into its own engine, but
that would slow down prototyping of an open source hardware documentation
solution (it can always be refactored at some point in the future). Anywho,
using just the tags and associated logic laid out for platypus, we'll
easily be able to build static hierarchies (org charts, fishbone diagrams,
mind maps, etc). Just use only states & bonds and tell Platyvue to render
it as a hierarchy. Alternatively, if you want to add a level of complexity,
you could actually represent the "nested" concept of the more detailed
features by using the dive/rise links to embed more detailed nodes inside
of more abstract nodes. That wouldn't be immediately intuitive to everyone,
but they should get it after a brief explanation.

**Comment by jmwright** [comment]
Regarding the feature tree - Correct. Here are a couple of other pages on tree data structures.

http://interactivepython.org/runestone/static/pythonds/Trees/implementation.html
http://interactivepython.org/runestone/static/pythonds/Trees/implementation.html

I like the idea of at least supporting dive/rise links in the feature tree. Seems like that would give you the flexibility to do whatever you needed.
